export const UNIDADES_MEDIDA = [
  { value: "TONELADA", label: "Tonelada" },
  { value: "MT", label: "MT (Tonelada métrica)" },
  { value: "LITRO", label: "Litro" },
  { value: "GALON", label: "Galón" },
  { value: "BARRIL", label: "Barril" },
  { value: "METRO_CUBICO", label: "m³" },
  { value: "KILO", label: "Kilogramo" },
  { value: "UNIDAD", label: "Unidad" },
  { value: "CAJA", label: "Caja" },
  { value: "PAQUETE", label: "Paquete" },
  { value: "METRO", label: "Metro" },
  { value: "HORA", label: "Hora" },
  { value: "DIA", label: "Día" },
  { value: "MES", label: "Mes" },
  { value: "SERVICIO", label: "Servicio" },
] as const

export const PUERTOS = [
  "Santa Marta",
  "Barranquilla",
  "Cartagena",
  "Buenaventura",
  "Tumaco",
  "Turbo",
  "Coveñas",
  "Pozos Colorados",
  "Mamonal",
  "Puerto Bolívar",
  "San Andrés",
  "Providencia",
] as const

export const PAIS_A_ISO: Record<string, string> = {
  "Alemania": "DE", "Angola": "AO", "Antigua y Barbuda": "AG", "Arabia Saudita": "SA",
  "Argelia": "DZ", "Argentina": "AR", "Armenia": "AM", "Australia": "AU", "Austria": "AT",
  "Azerbaiyán": "AZ", "Bahamas": "BS", "Baréin": "BH", "Bangladés": "BD", "Barbados": "BB",
  "Bélgica": "BE", "Belice": "BZ", "Benín": "BJ", "Bielorrusia": "BY", "Birmania": "MM",
  "Bolivia": "BO", "Bosnia y Herzegovina": "BA", "Botsuana": "BW", "Brasil": "BR",
  "Brunéi": "BN", "Bulgaria": "BG", "Burkina Faso": "BF", "Burundi": "BI", "Bután": "BT",
  "Cabo Verde": "CV", "Camboya": "KH", "Camerún": "CM", "Canadá": "CA", "Catar": "QA",
  "Chad": "TD", "Chile": "CL", "China": "CN", "Chipre": "CY", "Colombia": "CO", "Comoras": "KM",
  "Corea del Norte": "KP", "Corea del Sur": "KR", "Costa de Marfil": "CI", "Costa Rica": "CR",
  "Croacia": "HR", "Cuba": "CU", "Dinamarca": "DK", "Dominica": "DM", "Ecuador": "EC",
  "Egipto": "EG", "El Salvador": "SV", "Emiratos Árabes Unidos": "AE", "Eritrea": "ER",
  "Eslovaquia": "SK", "Eslovenia": "SI", "España": "ES", "Estados Unidos": "US", "Estonia": "EE",
  "Esuatini": "SZ", "Etiopía": "ET", "Filipinas": "PH", "Finlandia": "FI", "Fiyi": "FJ",
  "Francia": "FR", "Gabón": "GA", "Gambia": "GM", "Georgia": "GE", "Ghana": "GH",
  "Granada": "GD", "Grecia": "GR", "Guatemala": "GT", "Guinea": "GN", "Guinea Ecuatorial": "GQ",
  "Guinea-Bisáu": "GW", "Guyana": "GY", "Haití": "HT", "Honduras": "HN", "Hungría": "HU",
  "India": "IN", "Indonesia": "ID", "Irak": "IQ", "Irán": "IR", "Irlanda": "IE",
  "Islandia": "IS", "Islas Marshall": "MH", "Islas Salomón": "SB", "Israel": "IL",
  "Italia": "IT", "Jamaica": "JM", "Japón": "JP", "Jordania": "JO", "Kazajistán": "KZ",
  "Kenia": "KE", "Kirguistán": "KG", "Kiribati": "KI", "Kuwait": "KW", "Laos": "LA",
  "Lesoto": "LS", "Letonia": "LV", "Líbano": "LB", "Liberia": "LR", "Libia": "LY",
  "Liechtenstein": "LI", "Lituania": "LT", "Luxemburgo": "LU", "Madagascar": "MG",
  "Malasia": "MY", "Malaui": "MW", "Maldivas": "MV", "Malí": "ML", "Malta": "MT",
  "Marruecos": "MA", "Mauricio": "MU", "Mauritania": "MR", "México": "MX", "Micronesia": "FM",
  "Moldavia": "MD", "Mónaco": "MC", "Mongolia": "MN", "Montenegro": "ME", "Mozambique": "MZ",
  "Namibia": "NA", "Nauru": "NR", "Nepal": "NP", "Nicaragua": "NI", "Níger": "NE",
  "Nigeria": "NG", "Noruega": "NO", "Nueva Zelanda": "NZ", "Omán": "OM", "Países Bajos": "NL",
  "Pakistán": "PK", "Palaos": "PW", "Panamá": "PA", "Papúa Nueva Guinea": "PG", "Paraguay": "PY",
  "Perú": "PE", "Polonia": "PL", "Portugal": "PT", "Reino Unido": "GB",
  "República Centroafricana": "CF", "República Checa": "CZ", "República del Congo": "CG",
  "República Democrática del Congo": "CD", "República Dominicana": "DO", "Ruanda": "RW",
  "Rumania": "RO", "Rusia": "RU", "Samoa": "WS", "San Cristóbal y Nieves": "KN",
  "San Marino": "SM", "San Vicente y las Granadinas": "VC", "Santa Lucía": "LC",
  "Santo Tomé y Príncipe": "ST", "Senegal": "SN", "Serbia": "RS", "Seychelles": "SC",
  "Sierra Leona": "SL", "Singapur": "SG", "Siria": "SY", "Somalia": "SO", "Sri Lanka": "LK",
  "Suazilandia": "SZ", "Sudáfrica": "ZA", "Sudán": "SD", "Sudán del Sur": "SS",
  "Suecia": "SE", "Suiza": "CH", "Surinam": "SR", "Tailandia": "TH", "Tanzania": "TZ",
  "Tayikistán": "TJ", "Timor Oriental": "TL", "Togo": "TG", "Tonga": "TO",
  "Trinidad y Tobago": "TT", "Túnez": "TN", "Turkmenistán": "TM", "Turquía": "TR",
  "Tuvalu": "TV", "Ucrania": "UA", "Uganda": "UG", "Uruguay": "UY", "Uzbekistán": "UZ",
  "Vanuatu": "VU", "Vaticano": "VA", "Venezuela": "VE", "Vietnam": "VN", "Yemen": "YE",
  "Yibuti": "DJ", "Zambia": "ZM", "Zimbabue": "ZW",
}

export function getFlagEmoji(pais: string): string {
  const code = PAIS_A_ISO[pais]
  if (!code) return ""
  // Convert ISO code to flag emoji (Regional Indicator Symbols)
  return String.fromCodePoint(...code.split("").map((c) => 0x1F1E6 + c.charCodeAt(0) - 65))
}

export const BANDERAS = [
  "Alemania", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia",
  "Australia", "Austria", "Azerbaiyán", "Bahamas", "Baréin", "Bangladés", "Barbados", "Bélgica",
  "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana",
  "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya",
  "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Colombia", "Comoras",
  "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba",
  "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos",
  "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Esuatini",
  "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia",
  "Ghana", "Granada", "Grecia", "Guatemala", "Guinea", "Guinea Ecuatorial", "Guinea-Bisáu",
  "Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda",
  "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón",
  "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto",
  "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo",
  "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio",
  "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro",
  "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega",
  "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea",
  "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana",
  "República Checa", "República del Congo", "República Democrática del Congo",
  "República Dominicana", "Ruanda", "Rumania", "Rusia", "Samoa", "San Cristóbal y Nieves",
  "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe",
  "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia",
  "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza",
  "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga",
  "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda",
  "Uruguay", "Uzbekistán", "Vanuatu", "Vaticano", "Venezuela", "Vietnam", "Yemen", "Yibuti",
  "Zambia", "Zimbabue",
] as const
